const questions=[
['BÁSICA','Qual é o maior planeta do Sistema Solar?',['Terra','Júpiter','Marte','Vênus'],1,1000],['BÁSICA','Qual é a capital do Brasil?',['Rio de Janeiro','Brasília','Salvador','São Paulo'],1,2000],['BÁSICA','Quantos lados tem um triângulo?',['2','3','4','5'],1,3000],['BÁSICA','Qual animal é conhecido popularmente como “rei da selva”?',['Tigre','Leão','Lobo','Onça'],1,5000],['BÁSICA','Qual é o resultado de 7 × 8?',['54','56','64','48'],1,7000],['BÁSICA','Qual oceano banha a costa leste do Brasil?',['Pacífico','Índico','Atlântico','Ártico'],2,10000],['BÁSICA','Qual gás é mais abundante na atmosfera terrestre?',['Oxigênio','Nitrogênio','CO₂','Hélio'],1,15000],['BÁSICA','Qual instrumento possui teclas pretas e brancas?',['Violino','Piano','Flauta','Trompete'],1,20000],['BÁSICA','Em que continente fica o Egito?',['Europa','África','Ásia','Oceania'],1,30000],['BÁSICA','A água ferve, ao nível do mar, aproximadamente a:',['50 °C','80 °C','100 °C','120 °C'],2,40000],
['MÉDIA','Qual civilização construiu Machu Picchu?',['Maia','Asteca','Inca','Fenícia'],2,50000],['MÉDIA','Qual é o símbolo químico do ferro?',['Fe','Ir','F','Fr'],0,60000],['MÉDIA','Qual planeta possui os anéis mais conhecidos do Sistema Solar?',['Saturno','Urano','Netuno','Júpiter'],0,70000],['MÉDIA','Quem escreveu Dom Quixote?',['Cervantes','Dante','Shakespeare','Goethe'],0,80000],['MÉDIA','Qual é a unidade básica de informação digital?',['Byte','Bit','Pixel','Hertz'],1,90000],['MÉDIA','Qual país é atravessado pelo rio Nilo?',['Egito','Grécia','Turquia','Marrocos'],0,100000],['MÉDIA','A Revolução Industrial começou primeiro em qual país?',['França','Alemanha','Inglaterra','Itália'],2,120000],['MÉDIA','Qual órgão bombeia o sangue?',['Pulmão','Fígado','Coração','Rim'],2,140000],['MÉDIA','Qual é a raiz quadrada de 144?',['10','11','12','14'],2,160000],['MÉDIA','Qual é o maior oceano da Terra?',['Atlântico','Índico','Pacífico','Ártico'],2,180000],
['AVANÇADA','Qual processo produz ATP principalmente nas mitocôndrias?',['Fotossíntese','Respiração celular','Transcrição','Fermentação láctica'],1,220000],['AVANÇADA','Qual tratado encerrou formalmente a Primeira Guerra Mundial com a Alemanha?',['Tordesilhas','Versalhes','Utrecht','Brest-Litovsk'],1,260000],['AVANÇADA','Qual é o número atômico do carbono?',['6','8','12','14'],0,300000],['AVANÇADA','Qual império tinha Constantinopla como capital durante a maior parte de sua história?',['Romano do Oriente','Persa','Mongol','Cartaginês'],0,350000],['AVANÇADA','Em economia, inflação é principalmente:',['Queda geral de preços','Aumento geral e persistente do nível de preços','Aumento de produtividade','Queda da oferta monetária'],1,400000],['AVANÇADA','Qual camada da atmosfera concentra a maior parte do ozônio estratosférico?',['Troposfera','Estratosfera','Mesosfera','Termosfera'],1,500000],['AVANÇADA','Qual civilização desenvolveu a escrita cuneiforme na Mesopotâmia?',['Suméria','Inca','Minoica','Maia'],0,600000],['AVANÇADA','Qual princípio afirma que a energia não é criada nem destruída, apenas transformada?',['Inércia','Conservação da energia','Arquimedes','Exclusão de Pauli'],1,700000],['AVANÇADA','Qual é a unidade SI de resistência elétrica?',['Volt','Watt','Ohm','Ampere'],2,800000],['AVANÇADA','Em genética, qual molécula normalmente armazena a informação hereditária?',['ATP','DNA','Lipídio','Glicogênio'],1,1000000]
].map(x=>({d:x[0],q:x[1],a:x[2],c:x[3],p:x[4]}));
const reactions={good:['GÊNIO! Já pode jogar na Mega-Sena.','AÍ SIM! A plateia foi à loucura!','ACERTOU! O bilhão continua vivo.','Mandou bem!','Boa! Até a planta carnívora comemorou.'],bad:['ERROU! Ih... essa doeu.','Quase! A plateia fez “eeeeh...”.','OPA! Essa passou longe.','Não foi dessa vez. Bora seguir.','A planta carnívora julgou silenciosamente.'],end:['Belo jogo! O palco agradece.','Você encarou 30 perguntas. Respeito!','Resultado registrado no placar local.']};
const AV={masculino:{normal:'male-normal.png',wave:'male-wave.png',happy:'male-happy.png',sad:'male-sad.png',think:'male-think.png'},feminino:{normal:'female-normal.png',wave:'female-wave.png',happy:'female-happy.png',sad:'female-sad.png',think:'female-think.png'}};
const KEY='sdb14-ranking';
let state={index:0,correct:0,prize:0,streak:0,best:0,gender:'masculino',avatar:'masculino',avatarState:'normal',name:'Jogador',used50:false,usedSkip:false,usedAudience:false,answered:false};
const $=id=>document.getElementById(id); const money=n=>Number(n||0).toLocaleString('pt-BR');
function getRanking(){try{return JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('sdb13-ranking')||'[]')}catch{return []}}
function setRanking(v){localStorage.setItem(KEY,JSON.stringify(v))}
function avatarSrc(g,s='normal'){return `assets/${AV[g]?.[s]||AV[g].normal}`}
function navigate(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(id)?.classList.add('active-view');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='ranking')renderRanking();if(id==='achievements')renderAchievements();window.scrollTo({top:0,behavior:'smooth'});document.querySelector('.nav')?.classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
$('menuToggle')?.addEventListener('click',()=>document.querySelector('.nav')?.classList.toggle('open'));
function selectAvatar(g,s='normal'){state.avatar=g;state.avatarState=s;document.querySelectorAll('.avatar-option').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===g&&x.dataset.state===s));syncAvatar(s)}
function syncAvatar(s=state.avatarState){state.avatarState=s;const src=avatarSrc(state.avatar,s);['heroFemale','heroMale'].forEach(id=>$(id)&&($(id).src=id==='heroFemale'?avatarSrc('feminino','normal'):avatarSrc('masculino','normal')));if($('gameAvatar'))$('gameAvatar').src=src;if($('questionAvatar'))$('questionAvatar').src=src;if($('hostAvatar'))$('hostAvatar').src=avatarSrc(state.gender==='feminino'?'masculino':'feminino','normal')}
document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.gender=b.dataset.gender;if(state.gender==='feminino')selectAvatar('feminino','normal');else if(state.gender==='masculino')selectAvatar('masculino','normal');}));
document.querySelectorAll('.avatar-option').forEach(b=>b.addEventListener('click',()=>selectAvatar(b.dataset.avatar,b.dataset.state)));
function greeting(){const n=state.name;return state.gender==='feminino'?`Boa sorte, ${n}, garota!`:state.gender==='masculino'?`Boa sorte, ${n}, rapaz!`:`Boa sorte, ${n}!`}
$('startBtn').onclick=()=>{state={...state,index:0,correct:0,prize:0,streak:0,best:0,used50:false,usedSkip:false,usedAudience:false,answered:false,name:($('username').value.trim()||'Jogador').slice(0,18),gender:state.gender,avatar:state.avatar,avatarState:'normal'};['hint50','hintAudience','hintSkip'].forEach(id=>{if($(id))$(id).disabled=false});$('playerName').textContent=state.name;$('greeting').textContent=greeting();$('money').textContent='0';syncAvatar('normal');navigate('game');loadQuestion()};
function loadQuestion(){const q=questions[state.index];state.answered=false;state.avatarState='normal';$('roundLabel').textContent=`PERGUNTA ${state.index+1}/30`;$('progress').style.width=`${(state.index/30)*100}%`;$('difficulty').textContent=q.d;$('question').textContent=q.q;$('reaction').className='reaction';$('reaction').textContent='';$('nextBtn').classList.add('hidden');$('streak').textContent=`🔥 ${state.streak} sequência`;syncAvatar('normal');const wrap=$('answers');wrap.innerHTML='';q.a.forEach((text,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=`${String.fromCharCode(65+i)}) ${text}`;b.onclick=()=>answer(i,b);wrap.appendChild(b)});updatePrize()}
function answer(i,btn){if(state.answered)return;state.answered=true;const q=questions[state.index];document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(i===q.c){btn.classList.add('correct');state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);state.prize=q.p;react('good',reactions.good[Math.floor(Math.random()*reactions.good.length)]);syncAvatar('happy')}else{btn.classList.add('wrong');document.querySelectorAll('.answer')[q.c].classList.add('correct');state.streak=0;react('bad',reactions.bad[Math.floor(Math.random()*reactions.bad.length)]);syncAvatar('sad')}updatePrize();$('nextBtn').classList.remove('hidden');$('progress').style.width=`${((state.index+1)/30)*100}%`}
function react(kind,text){$('reaction').textContent=text;$('reaction').className=`reaction show ${kind}`}
$('nextBtn').onclick=()=>{if(state.index>=29)return finish();state.index++;loadQuestion()};
$('hint50').onclick=()=>{if(state.used50||state.answered)return;state.used50=true;const q=questions[state.index];let wrong=[0,1,2,3].filter(i=>i!==q.c).sort(()=>Math.random()-.5).slice(0,2);wrong.forEach(i=>document.querySelectorAll('.answer')[i].classList.add('disabled'));$('hint50').disabled=true;react('good','50:50! Duas alternativas saíram do jogo.')};
$('hintSkip').onclick=()=>{if(state.usedSkip||state.answered)return;state.usedSkip=true;$('hintSkip').disabled=true;if(state.index>=29)return finish();state.index++;loadQuestion();react('good','Pulou! A pergunta ficou para trás.')};
$('hintAudience').onclick=()=>{if(state.usedAudience||state.answered)return;state.usedAudience=true;$('hintAudience').disabled=true;const q=questions[state.index];const pick=Math.random()<.78?q.c:Math.floor(Math.random()*4);react('good',`A plateia votou: alternativa ${String.fromCharCode(65+pick)}!`)};
$('quitBtn').onclick=()=>{if(confirm('Sair da partida? O progresso atual será perdido.'))navigate('home')};
function updatePrize(){$('prize').textContent=money(state.prize);$('sidePrize').textContent=money(state.prize);$('money').textContent=money(state.prize)}
function finish(){const data=getRanking();data.push({name:state.name,score:state.prize,correct:state.correct,best:state.best,date:Date.now(),gender:state.gender,avatar:state.avatar});data.sort((a,b)=>b.score-a.score||b.correct-a.correct||b.best-a.best);setRanking(data.slice(0,30));$('resultPrize').textContent=`R$ ${money(state.prize)}`;$('resultCorrect').textContent=`${state.correct}/30`;$('resultBest').textContent=state.best;$('resultTitle').textContent=state.correct===30?'VOCÊ É O REI DO PALCO!':state.correct>=20?'MANDOU MUITO BEM!':state.correct>=10?'BOM JOGO!':'VALEU A TENTATIVA!';$('resultText').textContent=reactions.end[Math.floor(Math.random()*reactions.end.length)];navigate('result')}
$('restartBtn').onclick=()=>navigate('home');
function renderRanking(filter='all'){const box=$('rankingList');let data=getRanking();if(filter==='perfect')data=data.filter(x=>x.correct===30);if(!data.length){box.innerHTML='<div class="empty">Ainda não há resultados. Seja o primeiro a subir no placar!</div>';return}box.innerHTML=data.slice(0,20).map((x,i)=>`<div class="rank-row"><span class="rank-pos">#${i+1}</span><span class="rank-name">${escapeHtml(x.name)}</span><span class="rank-score">R$ ${money(x.score)}</span><span class="rank-correct">${x.correct}/30</span></div>`).join('')}
document.querySelectorAll('.rank-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.rank-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRanking(b.dataset.rank)});
function renderAchievements(){const data=getRanking();const best=Math.max(0,...data.map(x=>x.correct));const defs=[['👶','Primeiro passo','Faça sua primeira partida',data.length>0],['🎯','10 acertos','Acerte pelo menos 10 perguntas em uma partida',best>=10],['🔥','Sequência quente','Acerte pelo menos 15 perguntas',best>=15],['💎','Quase bilionário','Acerte pelo menos 20 perguntas',best>=20],['👑','Lenda do palco','Acerte todas as perguntas',best>=30],['💰','Caçador de prêmio','Chegue a R$ 1.000.000',data.some(x=>x.score>=1000000)]];$('achievementGrid').innerHTML=defs.map(x=>`<div class="panel achievement ${x[3]?'':'locked'}"><div class="icon">${x[0]}</div><b>${x[1]}</b><small>${x[2]}</small><div>${x[3]?'✓ DESBLOQUEADA':'🔒 BLOQUEADA'}</div></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('soundToggle').onchange=e=>localStorage.setItem('sdb14-sound',e.target.checked);$('motionToggle').onchange=e=>document.body.classList.toggle('no-motion',!e.target.checked);$('compactToggle').onchange=e=>document.body.classList.toggle('compact',e.target.checked);$('clearData').onclick=()=>{if(confirm('Apagar todo o ranking local?')){localStorage.removeItem(KEY);localStorage.removeItem('sdb13-ranking');renderRanking()}};
if(localStorage.getItem('sdb14-sound')==='false')$('soundToggle').checked=false;
// Estado inicial consistente
selectAvatar('masculino','normal');
