from pathlib import Path
p=Path('/mnt/data/v16/script.js')
s=p.read_text()
# Insert additions before TOPICS declaration (find const TOPICS)
marker='const TOPICS='
idx=s.index(marker)
extra=r'''
const EXTRA={
'Conhecimentos Gerais':[
['BÁSICA','Qual é o continente com maior área territorial?',['Ásia','África','Europa','Oceania'],0],['BÁSICA','Qual é a língua mais falada no mundo por número de falantes nativos?',['Inglês','Espanhol','Mandarim','Hindi'],2],['BÁSICA','Qual metal é líquido em temperatura ambiente?',['Ferro','Mercúrio','Cobre','Alumínio'],1],['BÁSICA','Quantos dias tem um ano bissexto?',['365','366','364','360'],1],['BÁSICA','Qual é o símbolo químico do ouro?',['Ag','Au','Gd','Or'],1],['MÉDIA','Qual país é conhecido como Terra do Sol Nascente?',['China','Coreia do Sul','Japão','Tailândia'],2],['MÉDIA','Qual é o menor número primo?',['0','1','2','3'],2],['MÉDIA','Qual camada da Terra é formada principalmente por ferro e níquel?',['Crosta','Manto','Núcleo','Litosfera'],2],['MÉDIA','Qual vitamina é produzida pela pele com exposição solar?',['A','B12','C','D'],3],['MÉDIA','Qual é a moeda oficial do Japão?',['Won','Yuan','Iene','Rupia'],2],['AVANÇADA','Qual filósofo escreveu A República?',['Aristóteles','Platão','Sócrates','Epicuro'],1],['AVANÇADA','Qual elemento possui número atômico 79?',['Prata','Ouro','Platina','Mercúrio'],1],['AVANÇADA','Qual é a velocidade aproximada da luz no vácuo?',['30 mil km/s','300 mil km/s','3 milhões km/s','3 mil km/s'],1],['AVANÇADA','Qual linguagem é conhecida por seu papel histórico na criação do Unix?',['C','Python','Ruby','Lua'],0],['AVANÇADA','Qual civilização utilizava o sistema de escrita hieroglífica no antigo Egito?',['Egípcia','Romana','Persa','Viking'],0],
['BÁSICA','Qual é o maior mamífero conhecido?',['Elefante africano','Baleia-azul','Girafa','Orca'],1],['BÁSICA','Qual planeta é o terceiro a partir do Sol?',['Marte','Terra','Vênus','Júpiter'],1],['BÁSICA','Quantos minutos há em uma hora?',['30','45','60','90'],2],['BÁSICA','Qual é a cor resultante da mistura de azul e amarelo?',['Roxo','Verde','Laranja','Marrom'],1],['BÁSICA','Qual oceano fica entre a África e a Austrália?',['Atlântico','Pacífico','Índico','Ártico'],2],['MÉDIA','Qual país tem a cidade de Marrakech?',['Marrocos','Egito','Tunísia','Argélia'],0],['MÉDIA','Qual é a unidade de frequência no SI?',['Newton','Hertz','Joule','Pascal'],1],['MÉDIA','Quem pintou Guernica?',['Dalí','Picasso','Miró','Goya'],1],['MÉDIA','Qual é a maior floresta tropical do mundo?',['Congo','Amazônia','Bornéu','Daintree'],1],['MÉDIA','Qual órgão produz insulina?',['Fígado','Pâncreas','Baço','Tireoide'],1],['AVANÇADA','Qual teorema relaciona os lados de um triângulo retângulo?',['Tales','Pitágoras','Fermat','Gauss'],1],['AVANÇADA','Qual cientista propôs a seleção natural junto a Darwin?',['Wallace','Faraday','Hubble','Fleming'],0],['AVANÇADA','Qual é a unidade SI de força?',['Joule','Watt','Newton','Pascal'],2],['AVANÇADA','Qual império tinha Tenochtitlán como capital?',['Inca','Asteca','Maia','Olmeca'],1],['AVANÇADA','Qual campo estuda a distribuição das populações no espaço?',['Demografia','Cartografia','Geologia','Taxonomia'],0]
],
'Música':[
['BÁSICA','Qual banda lançou “Smells Like Teen Spirit”?',['Nirvana','Pearl Jam','Soundgarden','Alice in Chains'],0],['BÁSICA','Qual banda gravou “Sweet Child o’ Mine”?',['Guns N’ Roses','Metallica','Aerosmith','Bon Jovi'],0],['BÁSICA','Qual cantor lançou o álbum “Views”?',['Drake','Lil Wayne','Lil Peep','Travis Scott'],0],['BÁSICA','Qual banda é conhecida pela música “Chop Suey!”?',['Slipknot','System of a Down','Korn','Deftones'],1],['BÁSICA','Qual cantora lançou “...Baby One More Time”?',['Madonna','Britney Spears','Adele','Beyoncé'],1],['MÉDIA','Qual banda lançou “Black” no álbum Ten?',['Pearl Jam','Nirvana','R.E.M.','Radiohead'],0],['MÉDIA','Qual grupo tem os irmãos Gallagher em sua formação histórica?',['Oasis','Blur','Pulp','Suede'],0],['MÉDIA','Qual rapper lançou “Lollipop” em 2008?',['Drake','Lil Wayne','Lil Peep','Eminem'],1],['MÉDIA','Qual artista é associado ao emo rap e ao álbum Come Over When You’re Sober, Pt. 1?',['Lil Peep','Drake','Post Malone','Future'],0],['MÉDIA','Qual banda lançou o álbum “City of Evil”?',['Avenged Sevenfold','Slipknot','Tool','Muse'],0],['AVANÇADA','Qual álbum do System of a Down contém “Aerials”?',['Toxicity','Mezmerize','Hypnotize','Steal This Album!'],0],['AVANÇADA','Qual álbum do Guns N’ Roses foi lançado em 1987?',['Appetite for Destruction','Use Your Illusion I','Chinese Democracy','G N’ R Lies'],0],['AVANÇADA','Qual músico foi baterista original do Nirvana antes de Dave Grohl?',['Chad Channing','Jimmy Chamberlin','Matt Cameron','Taylor Hawkins'],0],['AVANÇADA','Qual álbum do Pearl Jam foi lançado em 1993 e inclui “Daughter”?',['Vs.','Vitalogy','Yield','Binaural'],0],['AVANÇADA','Qual banda lançou “Psychosocial”?',['Slipknot','Korn','Disturbed','Avenged Sevenfold'],0],
['BÁSICA','Qual cantora é conhecida pelo álbum “1989”?',['Taylor Swift','Lady Gaga','Rihanna','Katy Perry'],0],['BÁSICA','Qual banda é famosa por “Enter Sandman”?',['Metallica','Megadeth','Slayer','Anthrax'],0],['BÁSICA','Qual cantor canadense lançou “Hotline Bling”?',['Drake','The Weeknd','Justin Bieber','Shawn Mendes'],0],['BÁSICA','Qual grupo tem a música “Bat Country”?',['Avenged Sevenfold','Slipknot','System of a Down','Limp Bizkit'],0],['BÁSICA','Qual cantora lançou “Rolling in the Deep”?',['Adele','Sia','Dua Lipa','Lorde'],0],['MÉDIA','Qual álbum do Nirvana foi lançado em 1991?',['Nevermind','In Utero','Bleach','MTV Unplugged'],0],['MÉDIA','Qual banda lançou o álbum “Toxicity” em 2001?',['System of a Down','Tool','Korn','Rage Against the Machine'],0],['MÉDIA','Qual cantor lançou o álbum “Tha Carter III”?',['Lil Wayne','Drake','Kendrick Lamar','Future'],0],['MÉDIA','Qual cantora lançou “Bad Guy”?',['Billie Eilish','Lana Del Rey','Ariana Grande','Miley Cyrus'],0],['MÉDIA','Qual banda ficou conhecida por “Duality”?',['Slipknot','Deftones','Muse','Placebo'],0],['AVANÇADA','Qual diretor de videoclipes dirigiu “November Rain” para Guns N’ Roses?',['Andy Morahan','David Fincher','Spike Jonze','Michel Gondry'],0],['AVANÇADA','Qual álbum do Pearl Jam contém “Jeremy”?',['Ten','Vs.','Yield','No Code'],0],['AVANÇADA','Qual álbum de Lil Peep foi lançado postumamente em 2019?',['Everybody’s Everything','Hellboy','Come Over When You’re Sober Pt. 1','Crybaby'],0],['AVANÇADA','Qual álbum do Avenged Sevenfold inclui “A Little Piece of Heaven”?',['Avenged Sevenfold','Nightmare','City of Evil','The Stage'],0],['AVANÇADA','Qual artista pop lançou o álbum “Future Nostalgia”?',['Dua Lipa','Ariana Grande','Lady Gaga','Olivia Rodrigo'],0]
],
'Cinema & TV':[
['BÁSICA','Quem dirigiu Pulp Fiction?',['Quentin Tarantino','Martin Scorsese','Francis Ford Coppola','David Lynch'],0],['BÁSICA','Quem dirigiu Taxi Driver?',['Martin Scorsese','Tarantino','Coppola','Brian De Palma'],0],['BÁSICA','Quem dirigiu O Poderoso Chefão?',['Francis Ford Coppola','Scorsese','Spielberg','George Lucas'],0],['BÁSICA','Quem dirigiu O Anjo Exterminador?',['Luis Buñuel','Ingmar Bergman','Akira Kurosawa','Federico Fellini'],0],['BÁSICA','Quem dirigiu Sete Samurais?',['Akira Kurosawa','Yasujiro Ozu','Bergman','Kieslowski'],0],['MÉDIA','Qual filme de Tarantino acompanha uma noiva em busca de vingança?',['Kill Bill','Jackie Brown','Reservoir Dogs','Django Livre'],0],['MÉDIA','Qual filme de Scorsese se passa principalmente entre mafiosos de Nova York?',['Os Bons Companheiros','O Aviador','Silêncio','Hugo'],0],['MÉDIA','Qual filme de Coppola acompanha a família Corleone?',['O Poderoso Chefão','Apocalypse Now','A Conversação','Drácula'],0],['MÉDIA','Qual diretor fez “Amor à Flor da Pele”?',['Wong Kar-wai','Kurosawa','Bergman','Fellini'],0],['MÉDIA','Qual cineasta sueco dirigiu “O Sétimo Selo”?',['Ingmar Bergman','Victor Sjöström','Lars von Trier','Roy Andersson'],0],['AVANÇADA','Qual filme de Wong Kar-wai é associado a Chow Mo-wan e Su Li-zhen?',['Amor à Flor da Pele','2046','Anjos Caídos','Chungking Express'],0],['AVANÇADA','Qual filme de Kurosawa apresenta uma história contada por diferentes perspectivas?',['Rashomon','Ikiru','Ran','Kagemusha'],0],['AVANÇADA','Qual filme de Bergman acompanha uma atriz e uma enfermeira em uma relação de identidade?',['Persona','Fanny e Alexander','Morangos Silvestres','Gritos e Sussurros'],0],['AVANÇADA','Qual filme de Scorsese é protagonizado por Travis Bickle?',['Taxi Driver','Touro Indomável','Cassino','A Última Tentação de Cristo'],0],['AVANÇADA','Qual filme de Coppola retrata a Guerra do Vietnã com a jornada do capitão Willard?',['Apocalypse Now','The Conversation','Peggy Sue','Rumble Fish'],0],
['BÁSICA','Qual filme cult de 1999 foi dirigido por David Fincher e baseado em Chuck Palahniuk?',['Clube da Luta','Seven','Zodíaco','A Rede Social'],0],['BÁSICA','Qual diretor fez “O Iluminado”?',['Stanley Kubrick','Ridley Scott','David Lynch','Roman Polanski'],0],['BÁSICA','Qual filme apresenta o personagem Donnie Darko?',['Donnie Darko','Memento','Oldboy','Eraserhead'],0],['BÁSICA','Qual diretor fez “Eraserhead”?',['David Lynch','John Carpenter','Terry Gilliam','Cronenberg'],0],['BÁSICA','Qual filme de Kubrick é sobre um hotel isolado?',['O Iluminado','Laranja Mecânica','Barry Lyndon','Nascido para Matar'],0],['MÉDIA','Qual diretor dirigiu “Chungking Express”?',['Wong Kar-wai','John Woo','Park Chan-wook','Edward Yang'],0],['MÉDIA','Qual filme de Kurosawa acompanha um senhor que reflete sobre sua vida após descobrir estar doente?',['Ikiru','Rashomon','Ran','Yojimbo'],0],['MÉDIA','Qual filme de Bergman trata de uma família teatral no início do século XX?',['Fanny e Alexander','Persona','O Silêncio','A Fonte da Donzela'],0],['MÉDIA','Qual filme de Tarantino mistura artes marciais, vingança e Uma Thurman?',['Kill Bill','Pulp Fiction','Jackie Brown','Os Oito Odiados'],0],['MÉDIA','Qual filme de Scorsese acompanha o boxeador Jake LaMotta?',['Touro Indomável','Cassino','O Rei da Comédia','Ilha do Medo'],0],['AVANÇADA','Qual diretor dirigiu “O Eclipse” e “A Aventura”?',['Michelangelo Antonioni','Fellini','Visconti','Pasolini'],0],['AVANÇADA','Qual filme de Wong Kar-wai se passa em parte em um futuro de memórias e hotéis?',['2046','Happy Together','Days of Being Wild','As Tears Go By'],0],['AVANÇADA','Qual filme de Kurosawa é uma adaptação de Macbeth?',['Trono Manchado de Sangue','Ran','Yojimbo','Dersu Uzala'],0],['AVANÇADA','Qual filme de Bergman inclui o encontro com a Morte em uma partida de xadrez?',['O Sétimo Selo','Persona','A Hora do Lobo','Sonata de Outono'],0],['AVANÇADA','Qual filme de Coppola é uma adaptação do romance de Bram Stoker?',['Drácula de Bram Stoker','Apocalypse Now','Cotton Club','Tucker'],0]
],
'História':[
['BÁSICA','Em que ano caiu o Muro de Berlim?',['1987','1989','1991','1975'],1],['BÁSICA','Em que ano terminou a Segunda Guerra Mundial?',['1943','1944','1945','1946'],2],['BÁSICA','Em que ano foi proclamada a República no Brasil?',['1822','1888','1889','1891'],2],['BÁSICA','Em que ano começou a Primeira Guerra Mundial?',['1912','1914','1918','1939'],1],['BÁSICA','Em que ano ocorreu a chegada portuguesa ao Brasil tradicionalmente datada?',['1492','1500','1530','1549'],1],['MÉDIA','Em que ano ocorreu a Revolução Russa de Outubro?',['1905','1914','1917','1922'],2],['MÉDIA','Em que ano foi assinada a Magna Carta?',['1066','1215','1453','1492'],1],['MÉDIA','Em que ano caiu Constantinopla?',['1204','1453','1492','1517'],1],['MÉDIA','Qual evento marcou o início da Reforma Protestante em 1517?',['Publicação das 95 Teses','Concílio de Trento','Paz de Augsburgo','Dieta de Worms'],0],['MÉDIA','Qual conferência reorganizou a Europa após as guerras napoleônicas?',['Viena','Berlim','Paris','Genebra'],0],['AVANÇADA','Em que ano foi assinada a Paz de Westfália?',['1618','1648','1688','1713'],1],['AVANÇADA','Qual batalha naval de 1571 foi decisiva contra a frota otomana?',['Lepanto','Trafalgar','Actium','Salamina'],0],['AVANÇADA','Qual dinastia governava a China durante a chegada de Matteo Ricci?',['Ming','Tang','Han','Song'],0],['AVANÇADA','Em que ano foi abolida a escravidão no Brasil pela Lei Áurea?',['1871','1885','1888','1889'],2],['AVANÇADA','Qual revolução começou em 1776 com a Declaração de Independência dos EUA?',['Revolução Francesa','Revolução Americana','Revolução Haitiana','Revolução Industrial'],1],
['BÁSICA','Qual foi o nome da pandemia de 1918?',['Gripe Espanhola','Peste Negra','Cólera Asiática','Gripe Suína'],0],['BÁSICA','Quem foi o primeiro presidente do Brasil?',['Deodoro da Fonseca','Floriano Peixoto','Prudente de Morais','Campos Sales'],0],['BÁSICA','Qual império tinha Roma como centro?',['Romano','Bizantino','Persa','Mongol'],0],['BÁSICA','Qual cidade foi destruída pela erupção do Vesúvio em 79 d.C.?',['Pompeia','Cartago','Tebas','Esparta'],0],['BÁSICA','Qual país lançou as bombas atômicas sobre Hiroshima e Nagasaki?',['URSS','Estados Unidos','Japão','Reino Unido'],1],['MÉDIA','Qual líder sul-africano foi preso por décadas e depois presidiu o país?',['Nelson Mandela','Desmond Tutu','Thabo Mbeki','Jomo Kenyatta'],0],['MÉDIA','Qual tratado de 1957 criou a Comunidade Econômica Europeia?',['Roma','Maastricht','Lisboa','Nice'],0],['MÉDIA','Qual país foi dividido em dois Estados em 1949?',['Alemanha','Coreia','Vietnã','Índia'],0],['MÉDIA','Qual foi a capital do Império Bizantino?',['Roma','Constantinopla','Antioquia','Alexandria'],1],['MÉDIA','Qual dinastia francesa foi derrubada na Revolução de 1789?',['Bourbon','Tudor','Habsburgo','Hohenzollern'],0],['AVANÇADA','Qual batalha de 732 é tradicionalmente associada à contenção do avanço omíada na Gália?',['Tours/Poitiers','Hastings','Manzikert','Agincourt'],0],['AVANÇADA','Qual documento inglês de 1689 limitou poderes da Coroa e reforçou o Parlamento?',['Bill of Rights','Petition of Right','Habeas Corpus Act','Act of Union'],0],['AVANÇADA','Qual revolução haitiana culminou na independência em 1804?',['Revolução Haitiana','Revolução Mexicana','Revolução Cubana','Revolução de 1848'],0],['AVANÇADA','Qual conferência de 1945 reuniu Roosevelt, Churchill e Stalin?',['Yalta','Versalhes','Bretton Woods','Bandung'],0],['AVANÇADA','Em que ano a Índia tornou-se independente do Reino Unido?',['1945','1947','1950','1952'],1]
],
'Ciência & Tecnologia':[
['BÁSICA','Qual cientista é associado à teoria da evolução por seleção natural?',['Darwin','Newton','Tesla','Pasteur'],0],['BÁSICA','Qual é o símbolo químico do sódio?',['So','Na','S','Sd'],1],['BÁSICA','Qual planeta possui anéis muito visíveis?',['Marte','Saturno','Mercúrio','Vênus'],1],['BÁSICA','Qual aparelho mede temperatura?',['Barômetro','Termômetro','Altímetro','Higrômetro'],1],['BÁSICA','Qual é a unidade de massa no SI?',['Quilo','Quilograma','Grama','Tonelada'],1],['MÉDIA','Qual cientista descobriu a penicilina?',['Alexander Fleming','Watson','Crick','Lavoisier'],0],['MÉDIA','Qual é o componente básico de uma célula eucariótica que contém o DNA?',['Núcleo','Ribossomo','Lisossomo','Centríolo'],0],['MÉDIA','Qual tecnologia converte luz em eletricidade em painéis solares?',['Efeito fotovoltaico','Indução magnética','Efeito Doppler','Fissão'],0],['MÉDIA','Qual é a unidade SI de energia?',['Newton','Joule','Watt','Volt'],1],['MÉDIA','Qual empresa criou o sistema operacional Android originalmente?',['Android Inc.','IBM','Nokia','Sun'],0],['AVANÇADA','Qual princípio quântico diz que não se pode conhecer simultaneamente posição e momento com precisão arbitrária?',['Incerteza de Heisenberg','Princípio de Pascal','Exclusão de Pauli','Equivalência'],0],['AVANÇADA','Qual cientista formulou a relatividade geral?',['Einstein','Bohr','Planck','Dirac'],0],['AVANÇADA','Qual partícula mediadora da força eletromagnética é prevista no Modelo Padrão?',['Fóton','Glúon','Nêutron','Múon'],0],['AVANÇADA','Qual algoritmo é classicamente associado à ordenação por divisão e conquista?',['Quicksort','Busca linear','BFS','Dijkstra'],0],['AVANÇADA','Qual linguagem foi criada por Guido van Rossum?',['Python','Java','C#','Go'],0],
['BÁSICA','Qual força nos mantém sobre a superfície da Terra?',['Gravidade','Atrito','Magnetismo','Pressão'],0],['BÁSICA','Qual órgão filtra o sangue e produz urina?',['Rim','Pulmão','Fígado','Pâncreas'],0],['BÁSICA','Qual gás é essencial à respiração aeróbica humana?',['Oxigênio','Hidrogênio','Hélio','Argônio'],0],['BÁSICA','Qual é o planeta mais próximo do Sol?',['Mercúrio','Vênus','Terra','Marte'],0],['BÁSICA','Qual dispositivo armazena dados de forma não volátil?',['SSD','RAM','Cache','Registrador'],0],['MÉDIA','Qual organela é conhecida como “usina de energia” da célula?',['Mitocôndria','Ribossomo','Golgi','Núcleo'],0],['MÉDIA','Qual fenômeno explica a mudança aparente de frequência causada pelo movimento relativo?',['Doppler','Compton','Fotoelétrico','Fissão'],0],['MÉDIA','Qual protocolo é fundamental para transferir páginas web?',['HTTP','FTP','SMTP','SSH'],0],['MÉDIA','Qual unidade mede potência?',['Watt','Joule','Newton','Ohm'],0],['MÉDIA','Qual componente eletrônico armazena carga em um campo elétrico?',['Capacitor','Resistor','Diodo','Transistor'],0],['AVANÇADA','Qual experimento confirmou a deflexão da luz por gravidade prevista pela relatividade geral?',['Eclipse de 1919','Michelson-Morley','Dupla fenda','Cavendish'],0],['AVANÇADA','Qual estrutura de dados usa o princípio FIFO?',['Fila','Pilha','Heap','Árvore'],0],['AVANÇADA','Qual sistema numérico é a base da computação digital moderna?',['Binário','Decimal','Octal','Romano'],0],['AVANÇADA','Qual é o nome do conjunto de instruções de um processador?',['ISA','API','GUI','ABI'],0],['AVANÇADA','Qual cientista propôs a ideia de um universo em expansão a partir de observações de galáxias?',['Edwin Hubble','Kepler','Tycho Brahe','Feynman'],0]
],
'Geografia & Brasil':[
['BÁSICA','Qual estado brasileiro tem a maior área territorial?',['Amazonas','Pará','Mato Grosso','Bahia'],0],['BÁSICA','Qual é a capital do Japão?',['Kyoto','Tóquio','Osaka','Nara'],1],['BÁSICA','Qual país é atravessado pelo rio Nilo em seu trecho mais conhecido?',['Egito','Espanha','Índia','México'],0],['BÁSICA','Qual é o ponto mais alto do Brasil?',['Pico da Neblina','Pico da Bandeira','Aconcágua','Monte Roraima'],0],['BÁSICA','Qual região brasileira abriga a maior parte da Amazônia Legal?',['Norte','Sul','Sudeste','Centro-Oeste'],0],['MÉDIA','Qual estado brasileiro possui o Pantanal em grande parte de seu território?',['Mato Grosso','Paraná','Ceará','Espírito Santo'],0],['MÉDIA','Qual país sul-americano não possui litoral?',['Bolívia','Chile','Peru','Uruguai'],0],['MÉDIA','Qual é a capital do Pará?',['Macapá','Belém','Manaus','Santarém'],1],['MÉDIA','Qual corrente marítima quente influencia a costa leste brasileira?',['Corrente do Brasil','Corrente de Humboldt','Corrente de Benguela','Corrente do Labrador'],0],['MÉDIA','Qual bioma é característico do semiárido nordestino?',['Caatinga','Pampa','Pantanal','Cerrado'],0],['AVANÇADA','Qual é o rio mais longo da América do Sul?',['Amazonas','Paraná','Orinoco','São Francisco'],0],['AVANÇADA','Qual país possui a maior extensão territorial da África?',['Argélia','Sudão','Líbia','República Democrática do Congo'],0],['AVANÇADA','Qual estreito separa a Ásia da América do Norte?',['Bering','Gibraltar','Malaca','Ormuz'],0],['AVANÇADA','Qual é a capital da Mongólia?',['Astana','Ulan Bator','Tashkent','Bishkek'],1],['AVANÇADA','Qual formação geográfica marca parte da fronteira entre Chile e Argentina?',['Andes','Alpes','Himalaia','Cárpatos'],0],
['BÁSICA','Qual é o menor estado brasileiro em área?',['Sergipe','Alagoas','Rio de Janeiro','Espírito Santo'],0],['BÁSICA','Qual cidade é conhecida como capital do Amazonas?',['Belém','Manaus','Boa Vista','Rio Branco'],1],['BÁSICA','Qual oceano banha a costa oeste da África?',['Atlântico','Pacífico','Índico','Ártico'],0],['BÁSICA','Qual país tem Lisboa como capital?',['Portugal','Espanha','Itália','Grécia'],0],['BÁSICA','Qual continente possui o deserto do Saara?',['África','Ásia','Austrália','América'],0],['MÉDIA','Qual país possui a maior população da América do Sul?',['Brasil','Argentina','Colômbia','Peru'],0],['MÉDIA','Qual é a capital do Chile?',['Santiago','Valparaíso','Lima','La Paz'],0],['MÉDIA','Qual cadeia montanhosa atravessa vários países da América do Sul?',['Andes','Rochosas','Alpes','Atlas'],0],['MÉDIA','Qual rio atravessa Paris?',['Sena','Tâmisa','Danúbio','Reno'],0],['MÉDIA','Qual país tem a região da Transilvânia?',['Romênia','Hungria','Polônia','Sérvia'],0],['AVANÇADA','Qual é o lago de água doce por área mais extenso do mundo?',['Superior','Vitória','Baikal','Tanganica'],0],['AVANÇADA','Qual canal liga o Mediterrâneo ao Mar Vermelho?',['Suez','Panamá','Kiel','Corinto'],0],['AVANÇADA','Qual rio forma parte da fronteira entre México e Estados Unidos?',['Rio Grande','Colorado','Mississippi','Yukon'],0],['AVANÇADA','Qual capital europeia está às margens do Danúbio e é dividida historicamente por Buda e Peste?',['Budapeste','Viena','Praga','Bratislava'],0],['AVANÇADA','Qual é o bioma brasileiro predominante no extremo sul do país?',['Pampa','Caatinga','Cerrado','Amazônia'],0]
],
'Literatura':[
['BÁSICA','Quem escreveu Dom Casmurro?',['Machado de Assis','José de Alencar','Eça de Queirós','Graciliano Ramos'],0],['BÁSICA','Quem escreveu Hamlet?',['Shakespeare','Milton','Dante','Goethe'],0],['BÁSICA','Quem escreveu Dom Quixote?',['Cervantes','Borges','Neruda','Lorca'],0],['BÁSICA','Quem escreveu O Pequeno Príncipe?',['Saint-Exupéry','Camus','Proust','Hugo'],0],['BÁSICA','Quem é o autor de Grande Sertão: Veredas?',['Guimarães Rosa','Clarice Lispector','Drummond','Jorge Amado'],0],['MÉDIA','Qual personagem narra Dom Casmurro?',['Bentinho','Brás Cubas','Quincas Borba','Eugênio'],0],['MÉDIA','Qual peça de Shakespeare apresenta o príncipe da Dinamarca?',['Hamlet','Macbeth','Otelo','Rei Lear'],0],['MÉDIA','Qual obra de Machado é narrada por um defunto autor?',['Memórias Póstumas de Brás Cubas','Quincas Borba','Esaú e Jacó','Helena'],0],['MÉDIA','Qual poeta espanhol escreveu “Romance sonámbulo”?',['Federico García Lorca','Antonio Machado','Cervantes','Unamuno'],0],['MÉDIA','Fernando Pessoa criou qual heterônimo ligado à poesia pastoril?',['Alberto Caeiro','Bernardo Soares','Ricardo Reis','Álvaro de Campos'],0],['AVANÇADA','Qual romance de Machado é marcado pelo narrador Brás Cubas?',['Memórias Póstumas de Brás Cubas','Dom Casmurro','Quincas Borba','Esaú e Jacó'],0],['AVANÇADA','Qual personagem de Shakespeare é um general veneziano?',['Otelo','Hamlet','Macbeth','Puck'],0],['AVANÇADA','Qual heterônimo de Pessoa escreveu “Ode Triunfal”?',['Álvaro de Campos','Ricardo Reis','Alberto Caeiro','Fernando Pessoa ortônimo'],0],['AVANÇADA','Qual obra de Lorca é uma tragédia sobre uma mãe e seus filhos em conflito com normas sociais?',['Yerma','Poeta em Nova York','Romanceiro Gitano','Impressões'],0],['AVANÇADA','Qual romance de Gabriel García Márquez acompanha várias gerações da família Buendía?',['Cem Anos de Solidão','O Amor nos Tempos do Cólera','Crônica de uma Morte Anunciada','O General em Seu Labirinto'],0],
['BÁSICA','Qual autor escreveu Crime e Castigo?',['Dostoiévski','Tolstói','Tchékhov','Turguêniev'],0],['BÁSICA','Quem escreveu A Divina Comédia?',['Dante Alighieri','Petrarca','Boccaccio','Virgílio'],0],['BÁSICA','Quem escreveu Orgulho e Preconceito?',['Jane Austen','Emily Brontë','George Eliot','Virginia Woolf'],0],['BÁSICA','Quem escreveu 1984?',['George Orwell','Aldous Huxley','Ray Bradbury','Philip K. Dick'],0],['BÁSICA','Quem escreveu Cem Anos de Solidão?',['Gabriel García Márquez','Mario Vargas Llosa','Borges','Cortázar'],0],['MÉDIA','Qual personagem é associado à obra Moby-Dick?',['Capitão Ahab','Jay Gatsby','Holden Caulfield','Raskólnikov'],0],['MÉDIA','Qual romance de Kafka acompanha Gregor Samsa?',['A Metamorfose','O Processo','O Castelo','Amerika'],0],['MÉDIA','Qual poeta escreveu Os Lusíadas?',['Luís de Camões','Fernando Pessoa','Eça de Queirós','Antero de Quental'],0],['MÉDIA','Qual personagem de Dom Quixote acompanha o protagonista?',['Sancho Pança','Hamlet','Lazarillo','Escamillo'],0],['MÉDIA','Qual obra de Dante descreve Inferno, Purgatório e Paraíso?',['Divina Comédia','Vita Nuova','Decameron','Il Canzoniere'],0],['AVANÇADA','Qual romance de James Joyce acompanha um dia na vida de Leopold Bloom?',['Ulisses','Finnegans Wake','Dublinenses','Retrato do Artista'],0],['AVANÇADA','Qual autor argentino escreveu “Ficções”?',['Jorge Luis Borges','Cortázar','Sabato','Bioy Casares'],0],['AVANÇADA','Qual romance de Virginia Woolf acompanha a personagem Clarissa Dalloway?',['Mrs Dalloway','Ao Farol','Orlando','As Ondas'],0],['AVANÇADA','Qual obra de Albert Camus apresenta Meursault?',['O Estrangeiro','A Peste','A Queda','O Mito de Sísifo'],0],['AVANÇADA','Qual autor peruano escreveu A Cidade e os Cachorros?',['Mario Vargas Llosa','García Márquez','Borges','Paz'],0]
],
'Política & Mundo':[
['BÁSICA','Quem foi presidente dos Estados Unidos durante grande parte da Crise dos Mísseis de Cuba?',['John F. Kennedy','Richard Nixon','Lyndon Johnson','Harry Truman'],0],['BÁSICA','Quem foi líder revolucionário cubano e governou Cuba por décadas?',['Fidel Castro','Fulgencio Batista','José Martí','Che Guevara'],0],['BÁSICA','Che Guevara nasceu em qual país?',['Argentina','Cuba','Bolívia','Uruguai'],0],['BÁSICA','Quem foi presidente do Brasil entre 1995 e 2002?',['Fernando Henrique Cardoso','José Sarney','Itamar Franco','Lula'],0],['BÁSICA','Quem presidiu o Brasil de 1985 a 1990?',['José Sarney','Tancredo Neves','Collor','FHC'],0],['MÉDIA','Qual foi o principal cargo de Che Guevara no governo revolucionário cubano antes de suas campanhas internacionais?',['Ministro da Indústria','Presidente','Chanceler','Prefeito de Havana'],0],['MÉDIA','Qual presidente brasileiro lançou o Plano Real durante seu governo?',['Itamar Franco','FHC','Sarney','Collor'],0],['MÉDIA','Qual presidente brasileiro venceu a eleição de 2002?',['Luiz Inácio Lula da Silva','Fernando Henrique Cardoso','José Serra','Itamar Franco'],0],['MÉDIA','Qual organização internacional foi criada em 1945?',['ONU','OTAN','UE','OEA'],0],['MÉDIA','Qual crise de 1962 envolveu mísseis soviéticos em Cuba?',['Crise dos Mísseis de Cuba','Crise de Suez','Crise do Congo','Crise de Berlim'],0],['AVANÇADA','Qual acordo encerrou formalmente a Guerra do Vietnã para os Estados Unidos em 1973?',['Acordos de Paz de Paris','Acordos de Camp David','Tratado de Tordesilhas','Acordos de Oslo'],0],['AVANÇADA','Qual presidente dos EUA anunciou a Doutrina Truman em 1947?',['Harry Truman','Kennedy','Eisenhower','Nixon'],0],['AVANÇADA','Qual líder soviético iniciou a política de glasnost e perestroika?',['Mikhail Gorbachev','Brejnev','Stalin','Khrushchev'],0],['AVANÇADA','Qual tratado criou formalmente a União Europeia em 1993?',['Tratado de Maastricht','Tratado de Roma','Tratado de Lisboa','Tratado de Nice'],0],['AVANÇADA','Qual conferência de 1955 é associada ao início do Movimento dos Países Não Alinhados?',['Bandung','Yalta','Bretton Woods','Potsdam'],0],
['BÁSICA','Quem foi presidente dos EUA durante o Watergate?',['Richard Nixon','Jimmy Carter','Gerald Ford','Ronald Reagan'],0],['BÁSICA','Quem foi o primeiro presidente eleito diretamente após a ditadura militar brasileira?',['Fernando Collor','Tancredo Neves','José Sarney','Itamar Franco'],0],['BÁSICA','Qual líder sul-africano tornou-se presidente em 1994 após o fim do apartheid?',['Nelson Mandela','F.W. de Klerk','Desmond Tutu','Thabo Mbeki'],0],['BÁSICA','Qual país teve Mao Zedong como principal líder revolucionário?',['China','Vietnã','Coreia do Norte','Mongólia'],0],['BÁSICA','Quem foi primeiro-ministro britânico durante grande parte da Segunda Guerra Mundial?',['Winston Churchill','Clement Attlee','Neville Chamberlain','Harold Macmillan'],0],['MÉDIA','Qual presidente dos EUA foi assassinado em Dallas em 1963?',['John F. Kennedy','Robert Kennedy','Abraham Lincoln','William McKinley'],0],['MÉDIA','Qual líder egípcio nacionalizou o Canal de Suez em 1956?',['Gamal Abdel Nasser','Anwar Sadat','Hosni Mubarak','Farouk'],0],['MÉDIA','Qual líder indiano foi associado à independência por meio da resistência não violenta?',['Mahatma Gandhi','Nehru','Jinnah','Tagore'],0],['MÉDIA','Qual primeiro-ministro britânica liderou o país na Guerra das Malvinas/Falklands?',['Margaret Thatcher','Theresa May','Clement Attlee','Harold Wilson'],0],['MÉDIA','Qual país foi governado por Augusto Pinochet após o golpe de 1973?',['Chile','Argentina','Peru','Uruguai'],0],['AVANÇADA','Qual documento de 1948 estabeleceu uma referência internacional para direitos humanos após a Segunda Guerra?',['Declaração Universal dos Direitos Humanos','Carta do Atlântico','Tratado de Roma','Convenção de Viena'],0],['AVANÇADA','Qual acordo de 1978 mediado pelos EUA tratou da paz entre Egito e Israel?',['Camp David','Oslo','Dayton','Lausanne'],0],['AVANÇADA','Qual líder iraniano retornou do exílio em 1979 durante a Revolução Iraniana?',['Ruhollah Khomeini','Mohammad Reza Pahlavi','Ali Khamenei','Mosaddegh'],0],['AVANÇADA','Qual presidente francês liderou a França Livre durante a Segunda Guerra Mundial?',['Charles de Gaulle','Georges Pompidou','François Mitterrand','René Coty'],0],['AVANÇADA','Qual líder chinês lançou as reformas econômicas a partir do fim dos anos 1970?',['Deng Xiaoping','Mao Zedong','Zhou Enlai','Hu Jintao'],0]
]};
for(const [k,v] of Object.entries(EXTRA)){if(raw[k]) raw[k].push(...v); else raw[k]=v;}
'''
s=s[:idx]+extra+s[idx:]
# Replace prize line
import re
s=re.sub(r"const PRIZES=\[[^\n]+", "const PRIZES=[1000,2000,3000,5000,7500,10000,20000,30000,40000,10000,20000,30000,40000,50000,60000,70000,80000,90000,95000,100000,150000,200000,300000,400000,500000,600000,700000,800000,900000,950000,1000000];", s, count=1)
# Better ladder: first 10 ends 10k; next 10 ends 100k; last 10 ends 1m. Fix above accidentally 10k at pos10 and then progression yes.
# Add topics by extending TOPICS literal after existing six using insertion before closing '};' immediately after Geografia entry
# Find the first occurrence after const TOPICS
start=s.index('const TOPICS=')
end=s.index('};',start)+2
old=s[start:end]
if "'Literatura'" not in old:
    old=old[:-2]+",\n 'Literatura':['📚','Literatura','Machado, Shakespeare, Pessoa, Lorca, clássicos e autores cult.'],\n 'Política & Mundo':['🌐','Política & Mundo','Personagens, líderes e acontecimentos da história política mundial e brasileira.']\n};"
    s=s[:start]+old+s[end:]
# valid banks 45, 15 each? 15 per difficulty now yes
s=s.replace("raw[t].length===15", "raw[t].length===45")
# build game 10 each difficulty and prizes 30
s=s.replace("shuffle(bank.filter(x=>x[0]===d)).forEach", "shuffle(bank.filter(x=>x[0]===d)).slice(0,10).forEach")
s=s.replace("questions.length!==15", "questions.length!==30")
# achievements and defaults total 30
s=s.replace("||15", "||30")
s=s.replace("total||15", "total||30")
s=s.replace("===15", "===30")
# State add errors/lives/retry
s=s.replace("state={index:0,correct:0,prize:0,streak:0,best:0,", "state={index:0,correct:0,errors:0,lives:3,prize:0,streak:0,best:0,")
s=s.replace("index:0,correct:0,prize:0,streak:0,best:0,used50", "index:0,correct:0,errors:0,lives:3,prize:0,streak:0,best:0,used50")
# Insert life update function and HTML hooks later
s=s.replace("function updateLifelines(){", "function updateLives(){const n=state.lives;$('lives').textContent='❤'.repeat(n)+'♡'.repeat(3-n);$('errors').textContent=`ERROS ${state.errors}/3`;$('lifeBar').style.width=`${(n/3)*100}%`}\nfunction updateLifelines(){")
# Answer wrong branch add errors and game over after feedback. 
s=s.replace("state.streak=0;syncStateAvatar('sad');react('bad',REACTIONS.bad[Math.floor(Math.random()*REACTIONS.bad.length)]);}", "state.streak=0;state.errors++;state.lives=Math.max(0,3-state.errors);syncStateAvatar('sad');react('bad',state.errors>=3?'ERROU! 3 erros. Fim de jogo.':REACTIONS.bad[Math.floor(Math.random()*REACTIONS.bad.length)]);}")
# timeout counts as error
s=s.replace("state.streak=0;syncStateAvatar('sad');react('bad','TEMPO ESGOTADO!", "state.streak=0;state.errors++;state.lives=Math.max(0,3-state.errors);syncStateAvatar('sad');react('bad',state.errors>=3?'TEMPO ESGOTADO! 3 erros. Fim de jogo.':'TEMPO ESGOTADO!")
# update lives on answer/timeout
s=s.replace("updateLifelines();}\nfunction syncStateAvatar", "updateLifelines();updateLives();}\nfunction syncStateAvatar")
# Need after wrong third error, next button should lead gameover not next. Modify next onclick and skip behavior separately.
s=s.replace("$('nextBtn').onclick=()=>{if(!state.answered)return;if(state.index>=state.questions.length-1)finish();else{state.index++;loadQuestion()}};", "$('nextBtn').onclick=()=>{if(!state.answered)return;if(state.errors>=3){finish(true);return}if(state.index>=state.questions.length-1)finish(false);else{state.index++;loadQuestion()}};")
# skip finish call
s=s.replace("if(state.index>=state.questions.length-1)finish();else{state.index++;loadQuestion()}", "if(state.index>=state.questions.length-1)finish(false);else{state.index++;loadQuestion()}")
# finish signature and title
s=s.replace("function finish(){if(state.finished)return;", "function finish(gameOver=false){if(state.finished)return;")
s=s.replace("{name:state.name,score:state.prize,correct:state.correct,best:state.best", "{name:state.name,score:state.prize,correct:state.correct,errors:state.errors,best:state.best")
s=s.replace("$('resultCorrect').textContent=`${state.correct}/${total}`;", "$('resultCorrect').textContent=`${state.correct}/${total}`;$('resultErrors').textContent=`${state.errors}/3`;")
s=s.replace("$('resultTitle').textContent=state.correct===total?'VOCÊ DOMINOU O PALCO!':state.correct>=10", "$('resultTitle').textContent=gameOver?'3 ERROS — FIM DE JOGO':state.correct===total?'VOCÊ DOMINOU O PALCO!':state.correct>=20")
# result text gameover
s=s.replace("$('resultText').textContent=REACTIONS.end[Math.floor(Math.random()*REACTIONS.end.length)];", "$('resultText').textContent=gameOver?'Você chegou ao limite de 3 erros. Respira, tenta de novo e busca o milhão!':REACTIONS.end[Math.floor(Math.random()*REACTIONS.end.length)];")
# startGame 30
s=s.replace("const questions=buildGameQuestions(state.topic);if(questions.length!==30)", "const questions=buildGameQuestions(state.topic);if(questions.length!==30)")
# update load and start lives
s=s.replace("updateMeter();updatePrize();updateLifelines();", "updateMeter();updatePrize();updateLifelines();updateLives();",1)
s=s.replace("updatePrize();updateLifelines();\n const wrap", "updatePrize();updateLifelines();updateLives();\n const wrap")
# retry button handler use home, and result stats defaults in html later
s=s.replace("$('restartBtn').onclick=()=>{state.finished=false;navigate('home')};", "$('restartBtn').onclick=()=>{state.finished=false;navigate('home')};\n $('retryBtn')?.addEventListener('click',()=>{state.finished=false;startGame()});")
# init validate old default 15 references
p.write_text(s)
