(()=>{const S={mode:"classic",name:"Jogador",gender:"masculino",qs:[],i:0,correct:0,wrong:0,lives:3,t:60,int:null,locked:false,helps:{fifty:false,audience:false,skip:false},streak:0};
const $=id=>document.getElementById(id), screens={home:$("home"),game:$("game"),result:$("result")};
const show=s=>{Object.values(screens).forEach(x=>x.classList.remove("active"));s.classList.add("active")};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const classicMoney=[100,200,500,1000,2000,5000,10000,15000,25000,10000,20000,30000,40000,50000,60000,70000,80000,90000,100000,100000,150000,200000,250000,300000,400000,500000,600000,700000,800000,1000000];
function start(mode){S.mode=mode;S.name=($("username").value.trim()||"Jogador").slice(0,18);S.qs=mode==="cult"?shuffle(QUESTION_BANK.cult):(()=>{let g={basic:[],medium:[],advanced:[]};QUESTION_BANK.classic.forEach(q=>g[q.difficulty].push(q));return [...shuffle(g.basic),...shuffle(g.medium),...shuffle(g.advanced)]})();S.i=0;S.correct=0;S.wrong=0;S.lives=3;S.streak=0;S.helps={fifty:false,audience:false,skip:false};show(screens.game);$("playerName").textContent=S.name;$("mode").textContent=mode==="cult"?"Desafio Cult":"Modo Clássico";setAvatar();load()}
function setAvatar(){$("gameAvatar").className="avatar "+(S.gender==="feminino"?"female":"male");$("gameAvatar").textContent=S.gender==="feminino"?"F":"M"}
function load(){clearInterval(S.int);S.locked=false;S.t=60;let q=S.qs[S.i];if(!q)return finish(true);$("number").textContent=`PERGUNTA ${S.i+1}`;$("progress").textContent=`${S.i+1}/${S.qs.length}`;$("fill").style.width=`${S.i/S.qs.length*100}%`;$("category").textContent=q.category;$("text").textContent=q.question;$("feedback").textContent="";$("timer").textContent="60";$("headerMoney").textContent=S.mode==="cult"?`CULT ×${Math.max(1,S.streak+1)}`:`R$ ${(classicMoney[S.i]||0).toLocaleString("pt-BR")}`;$("streak").textContent=S.mode==="cult"?`CULT ×${Math.max(1,S.streak+1)}`:"CLÁSSICO";let box=$("answers");box.innerHTML="";shuffle(q.answers.map((text,i)=>({text,i}))).forEach(x=>{let b=document.createElement("button");b.className="answer";b.dataset.i=x.i;b.textContent=x.text;b.onclick=()=>answer(x.i,b);box.appendChild(b)});lives();helps();S.int=setInterval(()=>{S.t--;$("timer").textContent=String(S.t).padStart(2,"0");if(S.t<=10)$("timer").style.background="#ffe7e5";if(S.t<=0){clearInterval(S.int);timeout()}},1000)}
function lives(){$("lives").textContent=["♥","♥","♥"].map((x,i)=>i<S.lives?x:"♡").join(" ")}
function helps(){$("fifty").disabled=S.helps.fifty;$("audience").disabled=S.helps.audience;$("skip").disabled=S.helps.skip||S.i===S.qs.length-1}
function lock(){document.querySelectorAll(".answer").forEach(b=>b.disabled=true)}
function answer(i,b){if(S.locked)return;S.locked=true;clearInterval(S.int);let q=S.qs[S.i];document.querySelectorAll(".answer").forEach(x=>{if(+x.dataset.i===q.correct)x.classList.add("correct")});if(i===q.correct){b.classList.add("correct");S.correct++;S.streak++;$("feedback").textContent=S.mode==="cult"?"🧠 Correto. Repertório em dia.":"🎉 Correto!"}else{b.classList.add("wrong");S.wrong++;S.lives--;S.streak=0;$("feedback").textContent="❌ Errou. Uma vida a menos.";lives()}lock();setTimeout(next,1000)}
function timeout(){if(S.locked)return;S.locked=true;S.wrong++;S.lives--;S.streak=0;lives();lock();$("feedback").textContent="⏰ Tempo esgotado!";let q=S.qs[S.i];document.querySelectorAll(".answer").forEach(x=>{if(+x.dataset.i===q.correct)x.classList.add("correct")});setTimeout(next,1000)}
function next(){if(S.lives<=0)return finish(false);if(S.i>=S.qs.length-1)return finish(true);S.i++;load()}
function fifty(){if(S.helps.fifty||S.locked)return;S.helps.fifty=true;let q=S.qs[S.i];shuffle([...document.querySelectorAll(".answer")].filter(b=>+b.dataset.i!==q.correct)).slice(0,2).forEach(b=>{b.disabled=true;b.style.opacity=".25"});helps()}
function audience(){if(S.helps.audience||S.locked)return;S.helps.audience=true;let q=S.qs[S.i],p=[0,0,0,0];p[q.correct]=60;let r=40;[0,1,2,3].filter(i=>i!==q.correct).forEach((i,n)=>{p[i]=n===2?r:Math.floor(Math.random()*(r+1));r-=p[i]});$("feedback").textContent=`👥 Plateia: A ${p[0]}% • B ${p[1]}% • C ${p[2]}% • D ${p[3]}%`;helps()}
function skip(){if(S.helps.skip||S.locked)return;S.helps.skip=true;clearInterval(S.int);lock();$("feedback").textContent="⏭ Pergunta pulada!";setTimeout(()=>{if(S.i<S.qs.length-1){S.i++;load()}else finish(true)},500)}
function finish(win){clearInterval(S.int);show(screens.result);$("icon").textContent=win?"🏆":"💔";$("title").textContent=win?(S.mode==="cult"?"DESAFIO CULT CONCLUÍDO!":"VOCÊ CHEGOU AO FINAL!"):"FIM DE JOGO";$("message").textContent=win?`${S.name}, você terminou a partida.`:`${S.name}, você atingiu 3 erros. Tente novamente.`;$("money").textContent=S.mode==="cult"?`${S.correct}/${S.qs.length}`:`R$ ${(S.i>=29?1000000:(classicMoney[Math.max(0,S.i-1)]||0)).toLocaleString("pt-BR")}`;$("correct").textContent=S.correct;$("wrong").textContent=S.wrong}
document.querySelectorAll(".avatarPick").forEach(b=>b.onclick=()=>{document.querySelectorAll(".avatarPick").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");S.gender=b.dataset.gender});
$("classic").onclick=()=>start("classic");$("cult").onclick=()=>start("cult");$("fifty").onclick=fifty;$("audience").onclick=audience;$("skip").onclick=skip;$("quit").onclick=()=>{clearInterval(S.int);show(screens.home)};$("retry").onclick=()=>start(S.mode);$("home").onclick=()=>show(screens.home);
})();